### ISSUE TITLE
Summary field in default options matcher shows "NaN"

### ISSUE THREAD

**Issue by mmgit** [Project60/org.project60.banking#301] opened 2020-08-04 11:45 UTC
the summary field allways shows **NaN** but should show the sum of the created contributions

![grafik](https://user-images.githubusercontent.com/1378433/89289830-2be33c80-d658-11ea-827f-e09212e5be8a.png)

**Comment by bjendres** [comment] 2021-04-08 14:53
Thanks @mmgit, it seems to work just fine, and I finally pulled this. I don't why it took so long for somebody else to be bothered by this...

**Comment by bjendres** [comment] 2021-04-08 14:54
will be released with ``0.8``

**Closed** 2021-04-08 14:53 UTC
Labels: bug, status:needs review

**Comment by jensschuppe** [comment] 2021-04-09 08:29
I had raised this in #254 already, which I'll mark as a duplicate of this.

Also, this issue seems to be `status:fixed`, right @bjendres?

**Comment by bjendres** [comment] 2021-04-09 12:05
> Also, this issue seems to be `status:fixed`, right @bjendres?

yes
